local mod = get_mod("Dense Onslaught")
local mutator = mod:persistent_table("Dense Onslaught")

Breeds = table.clone(mod.OriginalBreeds)
BreedPacks = table.clone(mod.OriginalBreedPacks)
BreedPacksBySize = table.clone(mod.OriginalBreedPacksBySize)
PackSpawningSettings = table.clone(mod.OriginalPackSpawningSettings)
RoamingSettings = table.clone(mod.OriginalRoamingSettings)
PacingSettings = table.clone(mod.OriginalPacingSettings)
IntensitySettings = table.clone(mod.OriginalIntensitySettings)
RecycleSettings = table.clone(mod.OriginalRecycleSettings)
HordeCompositions = table.clone(mod.OriginalHordeCompositions)
HordeCompositionsPacing = table.clone(mod.OriginalHordeCompositionsPacing)
HordeSettings = table.clone(mod.OriginalHordeSettings)
SpecialsSettings = table.clone(mod.OriginalSpecialsSettings)
GenericTerrorEvents = table.clone(mod.OriginalGenericTerrorEvents)
TerrorEventBlueprints = table.clone(mod.OriginalTerrorEventBlueprints)
BossSettings = table.clone(mod.OriginalBossSettings)
PatrolFormationSettings = table.clone(mod.OriginalPatrolFormationSettings)
UnitVariationSettings = table.clone(mod.OriginalUnitVariationSettings)
mod:dofile("scripts/settings/conflict_settings")
