local mod = get_mod("Dense Onslaught")

	-- Save existing horde tables
	mod.OriginalTerrorEventBlueprints = table.clone(TerrorEventBlueprints,true)
	mod.OriginalGenericTerrorEvents = table.clone(GenericTerrorEvents,true)
	mod.OriginalHordeCompositions = table.clone(HordeCompositions,true)
	mod.OriginalHordeCompositionsPacing = table.clone(HordeCompositionsPacing,true)
	mod.OriginalBreedPacks = table.clone(BreedPacks,true)
	mod.OriginalPackSpawningSettings = table.clone(PackSpawningSettings,true)
	mod.OriginalRecycleSettings  = table.clone(RecycleSettings,true)
	mod.OriginalPacingSettings = table.clone(PacingSettings,true)
	mod.OriginalSpecialsSettings = table.clone(SpecialsSettings,true)
	mod.OriginalBossSettings = table.clone(BossSettings,true)
	mod.OriginalBreedActions = table.clone(BreedActions,true)
	mod.OriginalBuffTemplates = table.clone(BuffTemplates,true)
	mod.OriginalBreedBehaviors = table.clone(BreedBehaviors,true)
	mod.OriginalBreedActions = table.clone(BreedActions,true)
	mod.OriginalBreeds = table.clone(Breeds,true)
	mod.OriginalUnitVariationSettings = table.clone(UnitVariationSettings,true)
	mod:echo(mod.OriginalSpecialsSettings)
