local mod = get_mod("Dense Onslaught")
mod:dofile("scripts/mods/Dense Onslaught/level_spawners/hooks")
local LevelSpawnerUtils = mod:dofile("scripts/mods/Dense Onslaught/level_spawners/level_spawners_utils")

LevelSpawnerUtils.initalize_custom_spawner("bell")
LevelSpawnerUtils.initalize_custom_spawner("cemetery")
LevelSpawnerUtils.initalize_custom_spawner("military")
LevelSpawnerUtils.initalize_custom_spawner("dlc_bogenhafen_city")
LevelSpawnerUtils.initalize_custom_spawner("dlc_bogenhafen_slum")
LevelSpawnerUtils.initalize_custom_spawner("dlc_portals")
LevelSpawnerUtils.initalize_custom_spawner("farmlands")
LevelSpawnerUtils.initalize_custom_spawner("forest_ambush")
LevelSpawnerUtils.initalize_custom_spawner("fort")
LevelSpawnerUtils.initalize_custom_spawner("ground_zero")
LevelSpawnerUtils.initalize_custom_spawner("magnus")
LevelSpawnerUtils.initalize_custom_spawner("military")
LevelSpawnerUtils.initalize_custom_spawner("mines")
LevelSpawnerUtils.initalize_custom_spawner("nurgle")
LevelSpawnerUtils.initalize_custom_spawner("skittergate")
LevelSpawnerUtils.initalize_custom_spawner("ussingen")
LevelSpawnerUtils.initalize_custom_spawner("warcamp")