local patrol_formation = {
    settings = PatrolFormationSettings.default_marauder_settings,
    normal = {
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_raider"
        },
        {
            "chaos_raider"
        },
        {
            "chaos_marauder",
            "chaos_marauder"
        },
        {
            "chaos_marauder",
            "chaos_marauder"
        },
        {
            "chaos_warrior"
        },
        {
            "chaos_marauder",
            "chaos_marauder"
        }
    },
    hard = {
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_warrior"
        },
        {
            "chaos_marauder",
            "chaos_marauder"
        },
        {
            "chaos_raider",
            "chaos_raider"
        },
        {
            "chaos_marauder",
            "chaos_marauder"
        },
        {
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        }
    },
    harder = {
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_raider",
            "chaos_raider"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        }
    },
    hardest = {
        {
            "chaos_raider"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_raider",
            "chaos_raider"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        }
    },
    -- Patrol Composition Changed From Dutch
    cataclysm = {
        {
            "chaos_raider",
            "chaos_raider"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_berzerker",
            "chaos_berzerker"
        },
        {
            "chaos_raider",
            "chaos_raider"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_berzerker",
            "chaos_berzerker"
        },
        {
            "chaos_raider",
            "chaos_raider"
        },
        {
            "chaos_berzerker",
            "chaos_berzerker"
        },
        {
            "chaos_warrior",
            "chaos_warrior"
        },
        {
            "chaos_marauder_with_shield",
            "chaos_marauder_with_shield"
        },
        {
            "chaos_raider",
            "chaos_raider"
        }
    }
}


return patrol_formation